-- ═══════════════════════════════════════════════════════════════
-- DIBUZZ DIGITAL — SUPABASE FULL SETUP & INTERNSHIP INSERT SCRIPT
-- Run this in: https://supabase.com/dashboard → SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- ── 1. CREATE TABLES (if not already existing) ────────────────

CREATE TABLE IF NOT EXISTS public.internships (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  company       TEXT DEFAULT 'DIBUZZ DIGITAL PRIVATE LIMITED',
  type          TEXT DEFAULT '3rd Semester Training',
  stipend       TEXT DEFAULT 'Flat ₹444',
  mode          TEXT DEFAULT 'Online / Hybrid Sprints',
  duration      TEXT DEFAULT '4 to 6 Weeks',
  openings      INT  DEFAULT 25,
  badge         TEXT DEFAULT '3rd Sem',
  skills        JSONB DEFAULT '[]'::jsonb,
  description   TEXT,
  image         TEXT,
  last_date     TEXT DEFAULT 'Enrollment Open',
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.courses (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           TEXT NOT NULL,
  category        TEXT NOT NULL,
  badge           TEXT,
  level           TEXT,
  duration        TEXT,
  rating          NUMERIC DEFAULT 4.9,
  reviews_count   INT DEFAULT 100,
  students_count  INT DEFAULT 0,
  original_price  NUMERIC NOT NULL DEFAULT 1499,
  price           NUMERIC NOT NULL DEFAULT 444,
  image           TEXT,
  description     TEXT,
  highlights      JSONB DEFAULT '[]'::jsonb,
  syllabus        JSONB DEFAULT '[]'::jsonb,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  email           TEXT UNIQUE NOT NULL,
  password        TEXT,
  phone           TEXT,
  role            TEXT DEFAULT 'student',
  joined_date     TEXT,
  college_reg_no  TEXT,
  college_name    TEXT,
  course          TEXT,
  branch          TEXT,
  profile_image   TEXT,
  enrolled_courses JSONB DEFAULT '[]'::jsonb,
  certificates    JSONB DEFAULT '[]'::jsonb,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.transactions (
  id          TEXT PRIMARY KEY,
  user_name   TEXT NOT NULL,
  user_email  TEXT NOT NULL,
  course_title TEXT NOT NULL,
  amount      NUMERIC NOT NULL,
  method      TEXT NOT NULL,
  status      TEXT DEFAULT 'SUCCESS',
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.certificates (
  certificate_id   TEXT PRIMARY KEY,
  student_name     TEXT NOT NULL,
  course_title     TEXT NOT NULL,
  completion_date  TEXT NOT NULL,
  grade            TEXT DEFAULT 'Grade A+',
  status           TEXT DEFAULT 'VERIFIED OFFICIAL',
  issued_by        TEXT DEFAULT 'DIBUZZ DIGITAL PRIVATE LIMITED',
  iso_cert         TEXT DEFAULT 'ISO 9001:2015 Certified Division',
  mca_cin          TEXT DEFAULT 'CIN: U73100BR2025PTC080924',
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.faqs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question    TEXT NOT NULL,
  answer      TEXT NOT NULL,
  category    TEXT DEFAULT 'General',
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- ── 2. ENABLE ROW LEVEL SECURITY ─────────────────────────────

ALTER TABLE public.internships   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faqs          ENABLE ROW LEVEL SECURITY;

-- ── 3. DROP OLD POLICIES (clean slate) ───────────────────────

DO $$ DECLARE r RECORD;
BEGIN
  FOR r IN SELECT policyname, tablename FROM pg_policies WHERE schemaname='public' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', r.policyname, r.tablename);
  END LOOP;
END $$;

-- ── 4. CREATE OPEN ACCESS POLICIES ───────────────────────────

-- INTERNSHIPS
CREATE POLICY "Read Internships"   ON public.internships FOR SELECT USING (true);
CREATE POLICY "Insert Internships" ON public.internships FOR INSERT WITH CHECK (true);
CREATE POLICY "Update Internships" ON public.internships FOR UPDATE USING (true);
CREATE POLICY "Delete Internships" ON public.internships FOR DELETE USING (true);

-- COURSES
CREATE POLICY "Read Courses"   ON public.courses FOR SELECT USING (true);
CREATE POLICY "Insert Courses" ON public.courses FOR INSERT WITH CHECK (true);
CREATE POLICY "Update Courses" ON public.courses FOR UPDATE USING (true);
CREATE POLICY "Delete Courses" ON public.courses FOR DELETE USING (true);

-- PROFILES
CREATE POLICY "Read Profiles"   ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Insert Profiles" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Update Profiles" ON public.profiles FOR UPDATE USING (true);
CREATE POLICY "Delete Profiles" ON public.profiles FOR DELETE USING (true);

-- TRANSACTIONS
CREATE POLICY "Read Transactions"   ON public.transactions FOR SELECT USING (true);
CREATE POLICY "Insert Transactions" ON public.transactions FOR INSERT WITH CHECK (true);
CREATE POLICY "Delete Transactions" ON public.transactions FOR DELETE USING (true);

-- CERTIFICATES
CREATE POLICY "Read Certificates" ON public.certificates FOR SELECT USING (true);
CREATE POLICY "Insert Certificates" ON public.certificates FOR INSERT WITH CHECK (true);

-- FAQS
CREATE POLICY "Read FAQs"   ON public.faqs FOR SELECT USING (true);
CREATE POLICY "Insert FAQs" ON public.faqs FOR INSERT WITH CHECK (true);
CREATE POLICY "Update FAQs" ON public.faqs FOR UPDATE USING (true);
CREATE POLICY "Delete FAQs" ON public.faqs FOR DELETE USING (true);

-- ── 5. INSERT ALL 8 INTERNSHIPS (clear first, then insert) ───

DELETE FROM public.internships;

-- Reset ID sequence so IDs start from 1 cleanly
ALTER SEQUENCE IF EXISTS public.internships_id_seq RESTART WITH 1;

INSERT INTO public.internships
  (title, company, type, stipend, mode, duration, openings, badge, skills, description, last_date)
VALUES
  (
    'Python Programming',
    'DIBUZZ DIGITAL PRIVATE LIMITED',
    '3rd Semester Training',
    'Flat ₹444',
    'Online / Hybrid Sprints',
    '4 to 6 Weeks',
    25,
    '3rd Sem',
    '["Python 3", "Data Structures", "OOPs", "APIs"]'::jsonb,
    'Industrial Python programming internship covering data structures, object-oriented concepts, and API integration.',
    'Enrollment Open'
  ),
  (
    'Web Development',
    'DIBUZZ DIGITAL PRIVATE LIMITED',
    '3rd Semester Training',
    'Flat ₹444',
    'Online / Hybrid Sprints',
    '4 to 6 Weeks',
    30,
    '3rd Sem',
    '["HTML5", "CSS3", "JavaScript", "React"]'::jsonb,
    'Build modern responsive websites and web application interfaces with real-world development practices.',
    'Enrollment Open'
  ),
  (
    'Artificial Intelligence (AI)',
    'DIBUZZ DIGITAL PRIVATE LIMITED',
    '3rd Semester Training',
    'Flat ₹444',
    'Online / Hybrid Sprints',
    '4 to 6 Weeks',
    20,
    '3rd Sem',
    '["AI Models", "Prompt Engineering", "OpenAI APIs", "LLMs"]'::jsonb,
    'Explore cutting-edge Artificial Intelligence models, prompt engineering techniques, and LLM API integrations.',
    'Enrollment Open'
  ),
  (
    'Machine Learning (ML)',
    'DIBUZZ DIGITAL PRIVATE LIMITED',
    '3rd Semester Training',
    'Flat ₹444',
    'Online / Hybrid Sprints',
    '4 to 6 Weeks',
    20,
    '3rd Sem',
    '["Python", "Scikit-Learn", "Pandas", "NumPy", "Models"]'::jsonb,
    'Practical Machine Learning internship covering data preprocessing, model building, and performance evaluation.',
    'Enrollment Open'
  ),
  (
    'Internet of Things (IoT)',
    'DIBUZZ DIGITAL PRIVATE LIMITED',
    '3rd Semester Training',
    'Flat ₹444',
    'Online / Hybrid Sprints',
    '4 to 6 Weeks',
    15,
    '3rd Sem',
    '["Sensors", "Arduino", "Raspberry Pi", "Cloud IoT"]'::jsonb,
    'Connect hardware sensors to cloud dashboards and automate smart IoT embedded system projects.',
    'Enrollment Open'
  ),
  (
    'AutoCAD',
    'DIBUZZ DIGITAL PRIVATE LIMITED',
    '3rd Semester Training',
    'Flat ₹444',
    'Online / Hybrid Sprints',
    '4 to 6 Weeks',
    25,
    '3rd Sem',
    '["2D Drafting", "3D Modeling", "Layouts", "Annotations"]'::jsonb,
    'Master industry-standard 2D drafting, architectural plans, and 3D CAD modeling in AutoCAD.',
    'Enrollment Open'
  ),
  (
    'SolidWorks',
    'DIBUZZ DIGITAL PRIVATE LIMITED',
    '3rd Semester Training',
    'Flat ₹444',
    'Online / Hybrid Sprints',
    '4 to 6 Weeks',
    20,
    '3rd Sem',
    '["3D CAD", "Part Modeling", "Assembly Design", "Simulation"]'::jsonb,
    'Comprehensive SolidWorks CAD design, mechanical part modeling, assembly creation, and simulation.',
    'Enrollment Open'
  ),
  (
    'MATLAB',
    'DIBUZZ DIGITAL PRIVATE LIMITED',
    '3rd Semester Training',
    'Flat ₹444',
    'Online / Hybrid Sprints',
    '4 to 6 Weeks',
    20,
    '3rd Sem',
    '["Simulink", "Data Processing", "Control Systems", "Signal Processing"]'::jsonb,
    'Numerical computing, matrix data processing, and system simulation using MATLAB & Simulink.',
    'Enrollment Open'
  );

-- ── 6. INSERT ADMIN PROFILE ───────────────────────────────────

INSERT INTO public.profiles (name, email, phone, role, joined_date, enrolled_courses, certificates)
VALUES (
  'Mananjay Prasad',
  'mananjayprasad7@gmail.com',
  '+91 9128458850',
  'admin',
  'Jan 01, 2025',
  '[]'::jsonb,
  '[]'::jsonb
)
ON CONFLICT (email) DO UPDATE
  SET name = EXCLUDED.name,
      phone = EXCLUDED.phone,
      role = EXCLUDED.role;

-- ── 7. VERIFY RESULTS ────────────────────────────────────────

SELECT id, title, badge, openings FROM public.internships ORDER BY id;
SELECT COUNT(*) AS total_internships FROM public.internships;
